/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_qiaoliang_JniOpencv */

#ifndef _Included_cloudeagle_com_groundstation_brigeCheck_JniOpencv
#define _Included_cloudeagle_com_groundstation_brigeCheck_JniOpencv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_qiaoliang_JniOpencv
 * Method:    CrackDetect
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cloudeagle_com_groundstation_brigeCheck_JniOpencv_CrackDetect
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
