/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_qiaoliang_JniOpencv */

#ifndef _Included_cloudeagle_com_groundstation_brigeCheck_JniOpencv
#define _Included_cloudeagle_com_groundstation_brigeCheck_JniOpencv
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
